spring:
  application:
    name: identity
  datasource:
    url: jdbc:postgresql://127.0.0.1:3242/mbanking_prod
    username: springdb
    password: ITE2@2024
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: "vannraruos@gmail.com"
    password: "klmcbchpzqszhlhz"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
logging:
  level:
    org:
      springframework:
        security: DEBUG